export const courseLogoSrc = [
  {
    courseName: "Бодифлекс",
    imgSrc: "/public/images/images_small/bodyflex_female_sm.png",
    bgColor: "bodyFlexColor",
  },
  {courseName: "StepAerobic",
    imgSrc: "/public/images/images_small/step_aerobic_sm.png",
    bgColor: "stepAerobicColor",
  },
 {courseName: "Stretching",
    imgSrc: "/public/images/images_small/stretching_female_sm.png",
    bgColor: "stretchingColor",
  },
  {courseName: "Yoga",
    imgSrc: "/public/images/images_small/yoga_female_sm.png",
    bgColor: "yogaColor",
  },
   {courseName: "Zumba",
    imgSrc: "/public/images/images_small/zumba_female_sm.png",
    bgColor: "zumbaColor",
  },
];
